/*
	테이블 생성, 변경, 삭제. 제약
	for pgsql 정원혁 2023.01
	
	https://www.postgresql.org/docs/current/transaction-iso.html
*/

--0. schema 설정;
set search_path to study; show search_path; SELECT session_user, current_database();

--1. 기존 테이블을 바탕으로 새 테이블 생성
select * 
into tmp1 
from orders o ;

select * from tmp1;

--2. 새로운 테이블 생성
create table 사람 (
	번호	int, 
 	이름	varchar(50)	not null,
 	폰번호	varchar(20)	null
);

alter table 사람 
	add 이메일	varchar(30)	null
;

select * from 사람;
insert into 사람 values (1, '이순신', '01012345678', 'me@abc.kr');
select * from 사람;
insert into 사람 values (1, '이순신', '01012345678', 'me@abc.kr');
select * from 사람;

drop table 사람;


--3. 새로운 테이블 생성. 제약과 함께
create table 사람 (
	번호	int	primary key, 
 	이름	varchar(50)	not null,
 	폰번호	varchar(20)	null,
	이메일	varchar(30)	unique null
);

--다음도 가능1
--create table 사람 (
--	번호	int, 
-- 	이름	varchar(50)	not null,
-- 	폰번호	varchar(20)	null,
--	이메일	varchar(30)	unique null,
--	constraint	pk_사람 primary key (번호)
--);

--다음도 가능2
--create table 사람 (
--	번호	int not null, 
-- 	이름	varchar(50)	not null,
-- 	폰번호	varchar(20)	null,
--	이메일	varchar(30)	unique null
--);
--ALTER TABLE 사람 ADD CONSTRAINT pk_사람 (번호);

insert into 사람 values (1, '이순신', '01012345678', 'me@abc.kr');
insert into 사람 values (1, '이순신', '01012345678', 'me@abc.kr');	--실패
insert into 사람 values (2, '이순신', '01012345678', 'me@abc.kr');	--실패
insert into 사람 values (2, '이순신', '01012345678', null);
insert into 사람 values (3, '이순신', '01012345678', null);		--성공
insert into 사람 values (4, '광개토', '01012345678', null);
select * from 사람;

--4. 판매 테이블 생성
CREATE TABLE study.판매 (
	판매번호 int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	판매일자 timestamptz NULL,
	고객번호 int4 NULL,
	금액 money NULL,
	수량 int2 NULL,
	CONSTRAINT 판매_pkey PRIMARY KEY ("판매번호")
);